[package]
edition = "2021"
name    = "migration"
publish = false
version = "0.1.0"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
entity = { path = "../entity" }
sea-schema = { version = "0.14.2", default-features = false, features = [
  "migration",
  "debug-print",
] }
