//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::{
    countries_regions::Entity as CountriesRegions,
    days::Entity as Days,
    provinces_states::Entity as ProvincesStates,
    seaql_migrations::Entity as SeaqlMigrations,
};
